### ISSUE TITLE
More contrast on badges

### ISSUE THREAD

**Issue by Xarkam** [tweakimp/jungle-night#1]
Hello, why not make badges foreground color more contrasted (with yellow) ?
![image](https://user-images.githubusercontent.com/331816/65634993-be01c980-dfdf-11e9-9983-363df57f3de2.png)
And bold font ?

**Comment by tweakimp** [comment]
I dont think it is possible to make the font bold.
A different color than the icons outline would interfere with them and take too much attention in my opinion.

**Comment by Xarkam** [comment]
It is for this reason that I proposed to put the text of the badge in color and not his background. (as is the case in the default theme)

In my personal opinion, badges are too much tone on tone and lose their purpose to inform the user.

You also have a problem with extension Remote WSL
![image](https://user-images.githubusercontent.com/331816/65667142-61ce9200-e03f-11e9-874c-125a312c859c.png)

**Comment by tweakimp** [comment]
I will look into changing the color of the badge.
The problem with the badge background color is that it is not possible to change the color of the clock icon that appears over the gear icon when you update. This is always white. So I have to choose a dark background color for the badge.
See https://github.com/microsoft/vscode/issues/44604
I fixed the extension colors. Should be up in some minutes.

**Comment by Xarkam** [comment]
I understand for the clock. It's something I never paid attention to.
In truth I am much more focused on the badges of files modified or not registered.

For wsl it's fixed :)
