### ISSUE TITLE
Missing color in snipped

### ISSUE THREAD

**Issue by Xarkam** [tweakimp/jungle-night#2]
Hi,
Tody I create a page web using html:5 snipped.
You ave missing color from fields (variable in snipped)
![image](https://user-images.githubusercontent.com/331816/65772700-07b2f700-e13b-11e9-894e-d31e30dfaddd.png)
And cursor as also pink color.

**Comment by tweakimp** [comment]
thank you, i will fix this

**Comment by tweakimp** [comment]
Fixed in https://github.com/tweakimp/jungle-night/commit/a0799d1110180f681a72e1925598f3721316476c

Seems like the border overlap though :/
![image](https://user-images.githubusercontent.com/20489521/65787938-5a4fdb80-e15a-11e9-841f-91404fc15af8.png)
