### ISSUE TITLE
minimap hint has same color

### ISSUE THREAD

**Issue by yoyoys** [tweakimp/jungle-night#3]
It's hard to define error and search results.

Jungle Night
<img width="373" alt="image" src="https://user-images.githubusercontent.com/22124891/67927529-ceffb500-fbf3-11e9-99dc-b3192840868c.png">

Ayu Mojave
<img width="322" alt="image" src="https://user-images.githubusercontent.com/22124891/67927592-f191ce00-fbf3-11e9-8f54-484cbc29cffb.png">

**Comment by tweakimp** [comment]
thank you, i will look into it

**Comment by tweakimp** [comment]
I tried to addres this here https://github.com/tweakimp/jungle-night/commit/6375c93c9e15ee0e83734f686a396396cf7ba9b8

let me know what you think :)

**Comment by yoyoys** [comment]
nice, when will you release it?

**Comment by tweakimp** [comment]
this should be live already, try to update the extension.
if this is still a problem, tell me :)
