### ISSUE TITLE
hardcoded color in your theme_writer.py

### ISSUE THREAD

**Issue by vinniec** [tweakimp/jungle-night#4]
is a nice theme, very nice colors, I'm just modifying it a bit to remove some color variation (too many colors confuse me) and make it darker, and I realized that you made a generator to try the changes.
At line 527 you left a color without variable:
`                "foreground": "#ccbb88"`
It also looks like the only color of this type, so maybe you did it deliberately.

**Comment by tweakimp** [comment]
Good catch, this was unintentional.
I will have a look and maybe use a color I use somewhere else already.
Can you show me your modified theme, maybe I can use some of your ideas :)

**Comment by vinniec** [comment]
Currently the changes I've made are not very well thought, since I prefer pure black because the eyes are less tired, I've tried to change most of the backgrounds of the theme in black.
one thing I had to change was the strings `editorUnnecessaryCode.border` really too strong (but it can be because I darkened the background).
I also removed the borders from the green and red colors of the diffs, they were too contrasting for me.

For the code highlighting, I really like the palette you chose, I'm just trying to remove some variations to have less colors.
Now I've unified the color of the classes with the color of the functions (which is the hardcoded in your generator file).
In addition I used the same color for the keywords and operators (I don't remember exactly, but for code `for x in y`, `for` had one color and `in` another and for me it was quite annoying).
I was thinking if it might make sense to do something about the arguments of the functions which are sometimes clay-colored and sometimes brownish (but maybe not).
another thing that I noticed are the characters backquoted in the strings in azure, but the color chosen is good and I'm not sure if I can improve.
Another thing that bothers me a bit is the `self` in red, but it is more or less like the backquote, maybe I can not do better.
I really like the color you chose for the comments and dockstrings!
I don't know, I think the changes I'm making are not very valid in a general sense but more in a specific sense that I'm always looking for something more minimal than normal.
I am also not sure that all the changes I have made have not created problems at some other point, in case I hope to notice and improve later.
I'll attach a screenshoot.

<a href="https://ibb.co/R3YSmsC"><img src="https://i.ibb.co/R3YSmsC/Istantanea-2019-11-20-14-40-47.png" alt="Istantanea-2019-11-20-14-40-47" border="0"></a>

**Comment by tweakimp** [comment]
> In addition I used the same color for the keywords and operators (I don't remember exactly, but for code `for x in y`, `for` had one color and `in` another and for me it was quite annoying).

[That is a bug.](https://github.com/microsoft/vscode/issues/85271) I want to fix this as well.

Thank you for your insights, I will look into choosing the same color for all python keywords (`self`, `class`, `def`, `for ...  in ...`), maybe that reduces some visual clutter.

**Comment by vinniec** [comment]
The rule for the `for` is this:
`
        {
            "name": "Keyword, Storage",
            "scope": [
                "keyword",
                "storage.modifier",
                "storage.type",
                "storage.type.class.js"
            ],
            "settings": {
                "foreground": "#FF8060"
            }
        },
`

The rule that contains the `in` and a lot of other operators is this:
`        
{
            "name": "Operator, Misc",
            "scope": [
                "constant.other.color",
                "keyword.operator",
                "keyword.other.substitution",
                "keyword.other.template",
                "punctuation",
                "punctuation.definition.tag",
                "punctuation.definition.tag.begin.html",
                "punctuation.definition.tag.end.html",
                "punctuation.definition.tag.html",
                "punctuation.section.embedded",
                "punctuation.separator.inheritance.php"
            ],
            "settings": {
                "foreground": "#608060"
            }
`

You can use the command `Developer: Inspect TM scopes` and point one keyword with  cursor, the penultimate field contains the `'scope':` of the section in the theme.json . 
Then in reality I didn't understand the bug and I don't know if it's a problem of how keywords are grouped, if that's the case then we have to study this page https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide .

**Comment by tweakimp** [comment]
Fixed in https://github.com/tweakimp/jungle-night/commit/816ccda7331da6db86d1d6b76e0b4df113a2ced5#diff-b4dc7cab5d4590129460dde52e52383fR468
