### ISSUE TITLE
wrong scrollbar color after update

### ISSUE THREAD

**Issue by yoyoys** [tweakimp/jungle-night#5]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/22124891/82733300-7cc7e200-9d45-11ea-89dd-e5d308a57239.png">
My vscode version
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/22124891/82733309-910bdf00-9d45-11ea-9d63-4521a575de55.png">

**Comment by tweakimp** [comment]
I will look into this, thanks

**Comment by tweakimp** [comment]
@yoyoys I fixed the scrollbar color for minimap scrollbars [here](https://github.com/tweakimp/jungle-night/commit/db9f85070b9f78ab005a3c87c002746d62c6dc12#diff-b4dc7cab5d4590129460dde52e52383fR140).
Can you tell me how to get to the second window?

**Comment by yoyoys** [comment]
@tweakimp Second image?

It Hyper terminal :)

https://hyper.is

**Comment by yoyoys** [comment]
And I've tested the new version, works fine. Thanks.
