### ISSUE TITLE
Issues with window.*border settings in the theme. 

### ISSUE THREAD

**Issue by wapenshaw** [tweakimp/jungle-night#6]
Hey! 

There is an issue with the theme when it comes to sidebar panels. They don't persist their locations across restart. I have noticed it when it started annoying me as other themes keep them where they are. 

Here is a recording of what the issue is. 
![uaPS1lYW6r](https://user-images.githubusercontent.com/739546/82772224-11a60a80-9e2e-11ea-9fc3-49bbdcd3f11c.gif)

I noticed this in my fork of your theme and I doubled checked with this too.  Same issue. 

I dug deep for hours and found these two values to be the issue.

```json
"window.activeBorder": "#00000000",
"window.inactiveBorder": "#00000000"
```

I have checked some other themes and they don't have window.* properties. 

I removed them from my theme and the timeline/outline panels stay where there are after restart. 

Not sure is this is an issue with VSCode or I am missing something about that setting.

**Comment by tweakimp** [comment]
You are right, this is probably a problem with VSCode. Can you create an issue there?
I will comment out this setting for the theme. I am not using it anyways.

**Comment by wapenshaw** [comment]
I reported it https://github.com/microsoft/vscode/issues/98615

Time to wait. 

Anyway, thanks for this theme! My absolute fav, can't use any other after this!

**Comment by tweakimp** [comment]
Im glad you like it :)
